import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "path";
import { readFileSync } from "fs";
import { generatePaletteCss, type Palette } from "./src/entities/site/paletteCss";
import { escapeHtml, siteHeadTags, type SiteIdentity } from "./src/entities/site/meta";

const SEED_PATH = path.resolve(__dirname, "src/content/settings/palette.json");
const SITE_SEED_PATH = path.resolve(__dirname, "src/content/settings/site.json");

/**
 * Bake the palette seed (src/content/settings/palette.json, the deployed
 * default, produced by the companion admin panel like any content file) into index.html:
 * a style tag so the first paint matches before any JS runs, plus the
 * browser-chrome theme-color metas. The runtime localStorage override in
 * src/lib/palette.ts appends after this block and outranks it.
 */
function paletteSeed(): Plugin {
  return {
    name: "palette-seed",
    transformIndexHtml(html) {
      const seed = JSON.parse(readFileSync(SEED_PATH, "utf8")) as Palette;
      const withMetas = html
        .replace(
          /(<meta name="theme-color" media="\(prefers-color-scheme: light\)" content=")[^"]*(")/,
          `$1${seed.light.background}$2`
        )
        .replace(
          /(<meta name="theme-color" media="\(prefers-color-scheme: dark\)" content=")[^"]*(")/,
          `$1${seed.dark.background}$2`
        );
      return {
        html: withMetas,
        tags: [
          {
            tag: "style",
            attrs: { id: "os-palette-seed" },
            children: generatePaletteCss(seed),
            injectTo: "head",
          },
        ],
      };
    },
  };
}

/**
 * Bake the site identity seed (src/content/settings/site.json, produced by
 * the companion admin panel like any content file) into index.html: the document title, the
 * description meta, and the Open Graph / Twitter card tags. The literals in
 * index.html are neutral template defaults that this plugin overwrites.
 */
function siteSeed(): Plugin {
  return {
    name: "site-seed",
    transformIndexHtml(html) {
      const seed = JSON.parse(readFileSync(SITE_SEED_PATH, "utf8")) as SiteIdentity;
      const withIdentity = html
        .replace(/<title>[^<]*<\/title>/, `<title>${escapeHtml(seed.title)}</title>`)
        .replace(
          /(<meta\s+name="description"\s+content=")[^"]*(")/,
          `$1${escapeHtml(seed.description)}$2`
        );
      return { html: withIdentity, tags: siteHeadTags(seed) };
    },
  };
}

/**
 * Emit a 404.html implementing the spa-github-pages redirect: GitHub Pages
 * serves it for any unknown path (deep links, hard refreshes), it encodes
 * the path into a query string and bounces to index.html, whose head snippet
 * (see index.html) restores the URL before the app boots. The number of
 * path segments to keep is derived from the configured base, so it works for
 * both root deploys and /repo/ project pages.
 */
function spaFallback(): Plugin {
  let base = "/";
  return {
    name: "spa-fallback-404",
    apply: "build",
    configResolved(config) {
      base = config.base;
    },
    generateBundle() {
      const segments = base.split("/").filter(Boolean).length;
      this.emitFile({
        type: "asset",
        fileName: "404.html",
        source: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Redirecting…</title>
    <script>
      // spa-github-pages: bounce unknown paths to index.html with the deep
      // link encoded in the query. Generated by vite.config.ts (spaFallback).
      var pathSegmentsToKeep = ${segments};
      var l = window.location;
      l.replace(
        l.protocol + "//" + l.hostname + (l.port ? ":" + l.port : "") +
        l.pathname.split("/").slice(0, 1 + pathSegmentsToKeep).join("/") +
        "/?/" +
        l.pathname.slice(1).split("/").slice(pathSegmentsToKeep).join("/").replace(/&/g, "~and~") +
        (l.search ? "&" + l.search.slice(1).replace(/&/g, "~and~") : "") +
        l.hash
      );
    </script>
  </head>
  <body></body>
</html>
`,
      });
    },
  };
}

/**
 * Vite Configuration
 * Configured for React + Tailwind v4
 */
export default defineConfig({
  plugins: [react(), tailwindcss(), paletteSeed(), siteSeed(), spaFallback()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 3000,
    // Fail loudly if 3000 is taken instead of hopping to 3001: localStorage
    // (theme, palette override, runtime edits) is per-origin, so a silent
    // port change looks like the site "forgot" its theme and settings.
    strictPort: true,
    open: true,
    watch: {
      // Playwright MCP writes logs/screenshots/downloads here; watching them
      // can crash the dev server (EBUSY on files still held by the browser).
      ignored: ["**/.playwright-mcp/**"],
    },
  },
  build: {
    outDir: "dist",
    sourcemap: false,
    rollupOptions: {
      output: {
        // The stable vendor libraries split into their own cached chunk, so editing
        // content or app code no longer invalidates the bytes that never changed.
        manualChunks: {
          vendor: ["react", "react-dom", "react-router-dom", "framer-motion"],
        },
      },
    },
  },
  base: process.env.VITE_BASE_PATH || "/",
});
